stages:
  - docker-build
  - test
before_script:
  - dockerservice=registry.docker.quancheng-ec.com:5000/manto-service:`TZ=CST-8 date '+%Y%m%d-%H%M'`
  - hostname -i
  - cd interface
  - time=$(date '+%Y%m%d%H%M')
  - sed -i "s/<time>/$time/" ./package.json
  - npm publish --access public
  - cd ../
  - whoami
sonar_analyze:
  stage: test
  script:
    - mvn sonar:sonar -Dsonar.host.url="http://sonar.quancheng-ec.com"  -Dsonar.java.binaries=target/sonar
  only:
    - master

build_images:
   stage: docker-build
   script:
    - echo $image
    - if [ "`docker images | awk '/^registry.docker.quancheng-ec.com:5000/ { print $3 }'`" ]; then docker rmi -f $(docker images | awk '/^registry.docker.quancheng-ec.com:5000/ { print $3 }' ); fi
    - mvn clean install -U
    - mvn deploy -N ;cd interface ; mvn deploy ; cd ..
    - echo "Build Docker Image..."
    - docker build --no-cache -t $dockerservice .
    - echo "Push Image:" $dockerservice " to repository..."
    - docker push $dockerservice
   only:
    - master
    - online_fly
